### PR TITLE
closes #20 closes #21 closes #22

### LINKED ISSUE #20: User links
As a signed in user
So I don't get confused
I don't want to see the sign in/sign up links.

### LINKED ISSUE #21: Only signed in users can signout
As a user of FamilyConnect
So I don't get confused
I don't want to see the sign out link unless I'm signed in.

### LINKED ISSUE #22: Only registered users can post
As a user of FamilyConnect
so I don't post events outside my account
I don't want to see the new post link unless I'm signed in.

### PR DESCRIPTION
**Pull request by hannako**

### CODE REVIEW

**Comment by Procras** [comment]
💩

**Comment by nomi811** [comment]
:shipit:

**Comment by bkluczynski-zz** [comment]
:shipit:

**Comment by cyberplanner** [comment]
:shipit:

**Pull request merged**
